import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/assets/css/globals.css";
import { QueryProvider } from "@/utils/query-providers";
import AuthProvider from "@/utils/auth-providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Geoportal ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>
        <QueryProvider>{children}</QueryProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
